export interface InvoiceRow {
  id: string;
  number: string;
  client_id: string;
  worker_id: string;
  notes: string | null;
  issued_at: Date | null;
  source_budget_id: string | null;
  client_snapshot_name: string;
  client_snapshot_tax_id: string;
  client_snapshot_phone: string | null;
  client_snapshot_email: string | null;
  client_snapshot_work_street: string;
  client_snapshot_work_city: string;
  client_snapshot_work_postal_code: string;
  client_snapshot_billing_street: string;
  client_snapshot_billing_city: string;
  client_snapshot_billing_postal_code: string;
  worker_snapshot_name: string;
  worker_snapshot_tax_id: string;
  worker_snapshot_phone: string | null;
  worker_snapshot_email: string | null;
  worker_snapshot_work_street: string;
  worker_snapshot_work_city: string;
  worker_snapshot_work_postal_code: string;
  worker_snapshot_billing_street: string;
  worker_snapshot_billing_city: string;
  worker_snapshot_billing_postal_code: string;
  tax_snapshot_name: string | null;
  tax_snapshot_rate: string | null;
  tax_snapshot_behavior: string | null;
  pricing_mode: "computed" | "manual-subtotal";
  manual_subtotal_amount: string | null;
  subtotal_amount: string;
  tax_amount: string;
  total_amount: string;
  created_at: Date;
  updated_at: Date;
}
